# Generated by Django 5.1 on 2024-09-21 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toffee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='toffee',
            name='title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
